Noovolari/leapp

README.md
**Changelog**
Minor change to the readme: I wrote the exact path of the log file which I found on my Windows 10 pc.
**Notes**
Hopefully the path is the same on all Windows systems.
I removed the `App Name` placeholder, as I think that it should always be `Leapp`. I wonder if it could be something different on MacOS/Linux.
Also, I don't know if the `{process type}` placeholder is relevant.
=> Update log file name for Windows on readme

src/app/components/aws-sso/aws-sso.component.html
**Changelog**
* Added placeholder example for AWS SSO Url in input field
Minor change to help make it clearer what the AWS SSO Url format should be.
=> feat: add placeholder example of AWS SSO Url

docs/use-cases/aws_iam_role.md, docs/use-cases/intro.md, src/app/services/session/aws/methods/aws-iam-role-federated.service.ts
This adds support for using AzureAD to Federate into AWS. Fixes #160.
**Changelog**
* Adds support for AzureAD Federation of AWS IAM Roles
=> feat: add support for aws azuread federation

src/app/components/session/session-card/detail.pipe.ts, src/app/components/session/session-card/session-card.component.html
**Changelog**
After resolving #166 the session & detail info can be too long to display. This adds a tooltip to make the full string visible.
Before:
After:
=> feat: add tooltip to show session & detail info

README.md
I've done my best to update the README links from defunct wiki to docs site.
Feel free to adjust.
=> docs: Update README links from defunct wiki to docs site

docs/installation/update-leapp.md
**Changelog**
Fixes update instructions.
**Bugfixes**
```
Error: This command updates brew itself, and does not take formula names.
Use `brew upgrade leapp` instead.
```
=> docs: Update update-leapp.md

README.md
Directly link the documentation for installing the app as the single source of truth. Improves the first impression when opening the repository to contribute :) (Context: Not everyone comes via the google -> website -> docs route)
**Notes**
Coming from the Hacker News thread: https://news.ycombinator.com/item?id=30102578
=> docs: Update URLs to installation docs in README

.github/CONTRIBUTING.md
**Changelog**
- Refine submit patches section
- Add sign-off example instructions (after the PR was submitted, also with multiple commits & rebase)
- Provide examples for convential commits (not everyone knows what they are from a first look)
=> docs: Refine contribution instructions

src/app/services/session/aws/methods/aws-iam-role-federated.service.ts
Signed-off-by: peteawood <build@duck.com>
**Changelog**
- Standard url for ADFS SAML Identity Provider supported for AWS IAM Role Federated sessions
Used the suggested approach in #200 to support the standard SAML 2.0 url used by ADFS 2.0 for NTLM authentication. The same url should be used by later versions of ADFS but this change has only been tested with 2.0.
The expected url format for ADFS is `https://<fqdn>/adfs/ls/IdpInitiatedSignOn.aspx.` For authentication with AWS, the query string `?loginToRp=urn:amazon:webservices` should be concatenated. 
By default the IdpInitiatedSignOnPage class accepts only the loginToRp parameter as a query string parameter but it is possible to modify the code to accept other query string parameters. 
Therefore the indexOf check in the …
=> feat: add support for adfs as a saml identity provider

packages/desktop-app/package.json
**Changelog**
Lowered User Account Control (UAC) required level in Windows version.
**Bugfixes**
Allows installation and usage if user doesn't have admin rights. #284
-
**Notes**
About different levels: https://docs.microsoft.com/en-us/cpp/build/reference/manifestuac-embeds-uac-information-in-manifest?view=msvc-170#remarks
If user belongs to Administrators group, installer will pop up an UAC window for privilege elevation, installation proceeds and application works.
If user does not belong to Administrators group but uses different account (eg. adm-user) for administrative tasks, installer will pop up the UAC window for privilege elevation, user needs to use adm-user credentials and application gets installed under adm-user's profile. When user starts the application, …
=> fix: Allow Windows installation without elevating privileges

docs/troubleshooting/faq.md
**Changelog**
Update symlink documentation.
**Bugfixes**
n/a
Update the docs for symlink to aws cli. The way it was previously worded, it sounded the opposite of what is happening.  
This PR updates the wording to be "FROM symlink TO actual binary."
It also gives examples to be as clear as possible. 
**Notes**
n/a
=> docs: Update symlink docs with clarification and examples.

packages/cli/src/commands/session/run-aws-credential-plugin.ts
Missing initialization of plugins when running from CLI with flags
**Bugfixes**
This is related to issue #340 by @bibli-alex. 
Please confirm the functionality
=> fix: issue #340

packages/core/src/services/integration/aws-sso-integration-service.ts
This commit fixes the case when the region for AWS SSO changes and the client isn't aware, leading to the "Session token not found or invalid" error.
It adds a check to see if the clients' region is different to the integration one and so recreate the client.
Signed-off-by: Mauricio Wyler <mwyler@ebowe.com>
**Changelog**
If SSO region changes the AWS SSO client is recreated
**Bugfixes**
[#360 ](url)
=> fix(#360): recreates AWS SSO client when the region changes

packages/core/src/services/aws-saml-assertion-extraction-service.spec.ts, packages/core/src/services/aws-saml-assertion-extraction-service.ts
**Changelog**
Fixes #374: patched `core` to support Keycloak URL
Authenticating through Keycloak Identity Provider now supported
=> fix(#374): support keycloak idp

packages/core/src/services/execute-service.ts
**Changelog**
Removed the seemingly unneeded usage of a hardcoded absolute path for the AWS and AZ CLIs on MacOS.
This allows users to install these binaries to arbitrary locations and not have to symlink them to `/usr/local/bin`, as long as they are on the $PATH.
**Bugfixes**
Previously, users had to symlink the AWS and/or AZ binaries to `/usr/local/bin`, because the path was hardcoded. This is not possible in all situations, such as when installing the dependencies with the Nix package manager, which does not keep the binaries in the typical locations.
**Notes**
I have successfully built and tested this change using `npm run build-and-run-dev` - it works fine on MacOS 13.3.1. But the note in the comment does sound very intentional and scary, so additional testing may be necessary.
If …
=> fix: do not prepend hardcoded path to command on darwin

docs/built-in-features/aws-ec2-connect.md, docs/built-in-features/general-options.md, docs/built-in-features/multi-console.md, docs/cli/scopes/help.md, docs/configuration.md, docs/configuring-integration/configure-aws-single-sign-on-integration.md, docs/configuring-integration/configure-azure-integration.md, docs/configuring-session/configure-aws-iam-role-chained.md, docs/configuring-session/configure-aws-iam-role-federated.md, docs/configuring-session/configure-aws-iam-user.md, docs/edit-session.md, docs/index.md, docs/installation/install-leapp.md, docs/installation/update-leapp.md, docs/integrations.md, docs/plugins/plugins-development.md, docs/plugins/plugins-introduction.md, docs/security/credential-process.md, docs/security/credentials-generation/aws.md, docs/security/credentials-generation/azure.md, docs/security/intro.md, docs/security/system-vault.md, docs/security/zero-knowledge.md, docs/sessions.md, docs/troubleshooting/faq.md, mkdocs.yml
**Changelog**
This PR includes a few small fixes in the documentation:
- makes formatting in certain sections more consistent with the rest of the docs
- standardizes metadata to be consistent with the markdown across sections
- corrects some spelling and grammatical issues
- removes duplicate sentence explaining integrations
- fixes broken link to the help plugin code
- fixes the rendering of fontawesome icons* and adds several more
**Notes**
*The fontawesome icons that aren't rendering (e.g., [here](https://docs.leapp.cloud/latest/sessions/)) were broken by removing the `pymdownx.emoji` configuration (see [this commit](https://github.com/Noovolari/leapp/commit/2ca7b30b3bb7d34fe737cb464731e91cb73ba56e#diff-98d0f806abc9af24e6a7c545d3d77e8f9ad57643e27211d7a7b896113e420ed2L112-L114)). If …
=> docs: correct several minor issues and grammatical or spelling mistakes

docs/configuring-session/configure-aws-iam-role-federated.md, packages/core/src/services/aws-saml-assertion-extraction-service.ts
**Changelog**
Add support for JumpCloud identity provider according to [Leapp docs](https://docs.leapp.cloud/latest/troubleshooting/faq/#how-can-i-add-support-to-a-new-saml-20-identity-provider).
=> Add support for JumpCloud identity provider

docs/configuration.md, docs/configuring-session/configure-localstack.md, mkdocs.yml, packages/core/src/services/cloud-provider-service.ts, packages/core/src/services/session/localstack/localstack-session-service.spec.ts, packages/desktop-app/src/app/components/dialogs/create-dialog/create-dialog.component.html, packages/desktop-app/src/app/components/sessions/session-card/session-card.component.ts
Hey folks 👋  - thanks so much for adding support for LocalStack, it looks awesome in the app, and works like a charm! 🚀 
I'd like to propose a few minor cosmetic changes in the docs and the labels in the app - using the CamelCase spelling `LocalStack` that we use for the product (instead of `Localstack`).
Keep up the great work! 🙌 
/cc @andreacavagna01 @ericvilla
=> docs: Update docs and labels to use proper casing of LocalStack

packages/core/src/services/aws-saml-assertion-extraction-service.ts
**Changelog**
- authentication URL regexp for Auth0 provider
**Bugfixes**
At the moment, the regexp used to check if the URL is an authentication URL for Auth0 checks if `/samlp` is in the URL. The correct one instead checks if `/u/login` is present.
This misconfiguration causes the opening of the login modal window for every credential refresh process because the `needAuthentication` method always resolves with `true`.
=> fix: change the authentication URL regexp for Auth0 provider

packages/core/src/services/web-console-service.spec.ts, packages/core/src/services/web-console-service.ts
**Changelog**
* Make Web Console URL log out from current browser session
This change to the Web Console URL makes AWS log out from any existing browser session, which avoids requiring a manual logout.
The implemented approach is based on [1] and its replies. It was found during testing that the sign-in links require the `us-east-1` domain prefix. Otherwise, the URL either redirects to the AWS Console landing page, or returns a 400 error.
Closes #309.
**Notes**
I tested this change with AWS SSO and many AWS accounts, in multiple regions for US and EU. I don't have access to any AWS GovCloud account, so it would be interesting if anyone can test this change and validate whether it works for GovCloud.
[1] https://serverfault.com/a/1097528
=> feat: make Web Console URL log out from current browser session
